Repository DroidWorksStudio/mLauncher, pull requests merged in 2022-12, with the labels that each got.

#32 App draw header
  app/build.gradle
  app/src/main/java/app/mlauncher/ui/AppDrawerFragment.kt
  app/src/main/res/layout/fragment_app_drawer.xml
  app/src/main/res/values/strings.xml
Labels: Feature request

#107 feat: resize the font in the settings
  app/src/main/java/app/mlauncher/data/Constants.kt
  app/src/main/java/app/mlauncher/ui/SettingsFragment.kt
  app/src/main/java/app/mlauncher/ui/compose/SettingsComposable.kt
  app/src/main/res/values-hdpi/dimens.xml
  app/src/main/res/values-xhdpi/dimens.xml
  app/src/main/res/values-xxhdpi/dimens.xml
  app/src/main/res/values-xxxhdpi/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Type: Enhancement, Status: Work In Progress

#106 Fixed the local to use from system settings
  app/src/main/java/app/mlauncher/MainActivity.kt
  app/src/main/java/app/mlauncher/data/Constants.kt
  app/src/main/java/app/mlauncher/ui/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
Labels: Type: Enhancement, Status: Work In Progress

#104 feat: put settings items on two rows
  app/src/main/java/app/mlauncher/ui/compose/SettingsComposable.kt
  app/src/main/res/layout/settings_button.xml
Labels: Type: Enhancement, Status: Work In Progress

#84 Added Backup/Restore
  README.md
  app/build.gradle
  app/src/main/java/app/mlauncher/MainActivity.kt
  app/src/main/java/app/mlauncher/data/Constants.kt
  app/src/main/java/app/mlauncher/data/Prefs.kt
  app/src/main/java/app/mlauncher/helper/Utils.kt
  app/src/main/java/app/mlauncher/ui/SettingsFragment.kt
  app/src/main/java/app/mlauncher/ui/compose/SettingsComposable.kt
  app/src/main/res/values/strings.xml
Labels: Type: Enhancement, Status: Work In Progress

#116 Feat: Added custom font size for settings
  app/build.gradle.kts
  app/src/main/kotlin/app/mlauncher/data/Prefs.kt
  app/src/main/kotlin/app/mlauncher/ui/AppDrawerAdapter.kt
  app/src/main/kotlin/app/mlauncher/ui/HomeFragment.kt
  app/src/main/kotlin/app/mlauncher/ui/SettingsFragment.kt
Labels: Type: Enhancement, Look & Feel, Status: Done

#120 cleanup: just some basic cleanup to the code base
  LICENSE
  app/build.gradle.kts
  app/src/main/kotlin/app/mlauncher/helper/Utils.kt
  app/src/main/kotlin/app/mlauncher/ui/HomeFragment.kt
  app/src/main/kotlin/app/mlauncher/ui/compose/SettingsComposable.kt
Labels: Type: Bug Report, Status: Done

#125 feat: Add the ability to change opacity of overlay
  app/src/main/java/app/mlauncher/MainViewModel.kt
  app/src/main/java/app/mlauncher/data/Prefs.kt
  app/src/main/java/app/mlauncher/ui/HomeFragment.kt
  app/src/main/java/app/mlauncher/ui/SettingsFragment.kt
  app/src/main/res/values-en-rCA/strings.xml
  app/src/main/res/values-en-rGB/strings.xml
  app/src/main/res/values-en-rUS/strings.xml
  app/src/main/res/values-iw-rIL/strings.xml
  app/src/main/res/values-ko-rKR/strings.xml
  app/src/main/res/values-night/array.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values-sr-rSP/strings.xml
  app/src/main/res/values-vi-rVN/strings.xml
  app/src/main/res/values/array.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Type: Enhancement, Status: Waiting For a Response, Look & Feel

#126 clean: cleanup for some minor changes.
  app/build.gradle.kts
  app/src/main/java/app/mlauncher/ui/SettingsFragment.kt
  app/src/main/java/app/mlauncher/ui/compose/SettingsComposable.kt
  art/get-it-on-github.png
  settings.gradle.kts
Labels: Type: Enhancement, Look & Feel, Status: Done

#130 cleanup: fix some code for opacity
  app/src/main/java/app/mlauncher/ui/HomeFragment.kt
  app/src/main/java/app/mlauncher/ui/SettingsFragment.kt
  app/src/main/java/app/mlauncher/ui/compose/SettingsComposable.kt
  app/src/main/res/values-night/array.xml
  app/src/main/res/values/array.xml
Labels: Type: Bug Report, Status: Done

#131 Update turkish translations + fix link on question.yml
  .github/ISSUE_TEMPLATE/QUESTION.yml
  app/src/main/res/values-tr-rTR/strings.xml
  fastlane/metadata/android/tr-TR/full_description.txt
  fastlane/metadata/android/tr-TR/short_description.txt
Labels: Type: Documentation, Status: Waiting For a Response
